name: Deploy to AWS ECR & AWS Lambda
# https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions
# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

on:
  push:
    branches: [main]

jobs:
  build:
    name: Building Container Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: custom-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker-cicd-github
        IMAGE_TAG: LATEST
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        
    - name: Update AWS Lambda function code with the latest container image
      id: update-lambda
      env:
        IMAGEURI: ${{ steps.custom-image.outputs.image }}
      run: |
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:957799101181:function:docker-cicd-github --image-uri 957799101181.dkr.ecr.us-east-1.amazonaws.com/docker-cicd-github:LATEST
